### ISSUE TITLE
没有_base

### ISSUE THREAD

**Issue by JIMhackKING** [lijiejie/BBScan#10]
AttributeError: 'module' object has no attribute '_base'
这个是什么问题？

**Comment by lijiejie** [comment]
请提供完整的traceback，不只是这一行

**Comment by JIMhackKING** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\IT\BBScan-master\BBScan.py", line 13, in
<module>
    from bs4 import BeautifulSoup
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "C:\Python27\lib\site-packages\bs4\builder\__init__.py", line 311, in <mo
dule>
    from . import _html5lib
  File "C:\Python27\lib\site-packages\bs4\builder\_html5lib.py", line 57, in <mo
dule>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by lijiejie** [comment]
可以试试  pip install --upgrade html5lib==1.0b8
