### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by wifislax** [lijiejie/BBScan#13]
[09:57:13] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

**Comment by lijiejie** [comment]
能否附上执行时的参数和操作系统平台

**Comment by wifislax** [comment]
root@kali:/opt/pentest/BBScan# python BBScan.py -f targets/domain.txt
[11:12:31] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

**Comment by wifislax** [comment]
root@kali:/opt/pentest/BBScan# python BBScan.py --host 10.226.248.12
[11:13:55] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable

**Comment by lnyzx** [comment]
OSX下也出现了这个错误
`python bbscan.py --host www.baidu.com
[16:59:42] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 35] Resource temporarily unavailable
Traceback (most recent call last):
  File "bbscan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 35] Resource temporarily unavailable`

**Comment by lucyxss** [comment]
╰─➤  python BBScan.py --host 127.0.0.1:99
[15:24:29] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 35] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 35] Resource temporarily unavailable

**Comment by a4m** [comment]
这个问题应该是个通用的问题

**Comment by lucyxss** [comment]
姐姐看这个http://blog.csdn.net/moxiaomomo/article/details/17308775

**Comment by lucyxss** [comment]
socket.setdefaulttimeout 把这个注释就不会报错了。

**Comment by a4m** [comment]
@lucyxss 我在Ubuntu 16.04 LTS 上测试了一下，注释了 42行的 `socket.setdefaulttimeout(30)` ，发现并没有解决这个问题。你电脑上测试结果怎么样？
```bash
╰─➤  cat BBScan.py -n|grep setdef             
    42	#socket.setdefaulttimeout(30)
╭─mark@wooyun /tmp/BBScan-master  
╰─➤  python BBScan.py --host mail.lib.dlut.edu.cn
[17:12:24] Batch Web Scan start.
[__main__.exception] <type 'exceptions.IOError'> [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable
╭─mark@wooyun /tmp/BBScan-master  
╰─➤  
```

**Comment by lucyxss** [comment]
@a4m 

#from gevent import monkey
#monkey.patch_all(thread=False)
#monkey.patch_socket()
#socket.setdefaulttimeout(30)
这几行注释


http://blogs.candoerz.com/question/148701/cherrypy-multiprocessing-and-gevent-monkey-patching.aspx  可能是看到这个加上了这个头。

暂时这样解决。能用就行

**Comment by lijiejie** [comment]
感谢各位， 我系统上还没出现过。 尽快测试解决

**Comment by smallmeet** [comment]
win7没出现问题,ubuntu,kali, mac os IOError: [Errno 11] Resource temporarily unavailable

**Comment by bmf4ck** [comment]
[__main__.exception] <type 'exceptions.IOError'> [Errno 11] Resource temporarily unavailable
Traceback (most recent call last):
  File "BBScan.py", line 656, in <module>
    q_results = multiprocessing.Manager().Queue()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 667, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 565, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 432, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable
注释掉socket.setdefaulttimeout也不行。。。

**Comment by bmf4ck** [comment]
monkey.patch_all(thread=False)
monkey.patch_socket()
这两行注释了就可以。。

**Comment by lijiejie** [comment]
已Fix

**Comment by tuhaolam** [comment]
目前在centos上还会重现该bug，只好注释socket.setdefaulttimeout(30)，结果还是不行。。
```
Process Process-6:
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "BBScan.py", line 573, in scan_process
    q_results.put((host, results))
  File "<string>", line 2, in put
  File "/usr/local/python/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/local/python/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/local/python/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/local/python/lib/python2.7/multiprocessing/connection.py", line 413, in answer_challenge
    message = connection.recv_bytes(2560000)         # reject large message
IOError: [Errno 11] Resource temporarily unavailable
```
