### ISSUE TITLE
昨天更新的存在依赖问题

### ISSUE THREAD

**Issue by tuian** [lijiejie/BBScan#15]
下面是报错

```c
Traceback (most recent call last):
  File "BBScan.py", line 30, in <module>
    from lib.connectionPool import HTTPConnPool, HTTPSConnPool
  File "/yourfolder/github/BBScan/lib/connectionPool.py", line 5, in <module>
    from urllib3.packages.six.moves.queue import Empty
ImportError: No module named six.moves.queue
```
尝试`pip install six`,未果。
谷歌未果。。。

**Comment by tuian** [comment]
解决，脑残了。。。

```c
 proxychains pip install requests -U
```

**Comment by lijiejie** [comment]
解决了就好
