### ISSUE TITLE
httpx库兼容性

### ISSUE THREAD

**Issue by jjjxusbx** [lijiejie/BBScan#62]
因为httpx库的新版本中已经移除了proxies参数
`root@instance-ruM4iC2D:~/tools/BBScan# python3 BBScan.py --host target.cn --api`
* BBScan v3.0  https://github.com/lijiejie/BBScan *
[15:04:12] 2 scan process started
[15:04:12] Domain lookup start.
Traceback (most recent call last):
  File "BBScan.py", line 1113, in main
    await asyncio.gather(*all_process)
  File "BBScan.py", line 798, in scan_process
    ret = await s.init_from_url(target['target'])
  File "BBScan.py", line 130, in init_from_url
    await self.init_final()
  File "BBScan.py", line 187, in init_final
    self.conn_pool = httpx.AsyncClient(headers=conf.default_headers,
TypeError: __init__() got an unexpected keyword argument 'proxies'
[15:04:12] Scan https://webexp.zhongxi.cn
[15:04:12] [main.exception] <class 'TypeError'> __init__() got an unexpected keyword argument 'proxies'

* No vulnerabilities found on sites in hosts.
![image](https://github.com/user-attachments/assets/3821158c-57da-49ca-9c0c-1ea2c6409b38)
在httpx请求中设置代理，貌似也没有解决问题

requirements.txt
![image](https://github.com/user-attachments/assets/88ea2fd8-437a-402c-987f-bf904b5ab741)

**Comment by lijiejie** [comment]
感谢反馈， 我已更新requirements.txt   指定旧版本了
你可以试试重新安装低版本

pip3 uninstall httpx   
pip3 install httpx==0.27.0

**Comment by jjjxusbx** [comment]
欧克
